### ISSUE TITLE
Cannot run due to PackageNotFoundError

### ISSUE THREAD

**Issue by mike-lloyd03** [Vimjas/vint#379]
`vint` returns the following error whenever it is invoked.

```
$ cat .vimrc | vint
Traceback (most recent call last):
  File "/usr/bin/vint", line 33, in <module>
    sys.exit(load_entry_point('vim-vint==0.4a4.dev10+g471e70b', 'console_scripts', 'vint')())
  File "/usr/bin/vint", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for vim-vint
```
vint version: vint-git 0.4a4.dev10+g471e70b-1 (installed from AUR)
OS: Manjaro Linux 5.15.12
System Python3 version: 3.10.1

This was working a few weeks ago so I think it has something to do with an update to Python 3.10 or perhaps one of the [ongoing issues with pip on Arch](https://github.com/pypa/pip/issues/10750#issuecomment-1001222324)

**Comment by mike-lloyd03** [comment]
I just tried cloning the master branch and now vint seems to work, but it cannot read from stdin.

```
$ vint --version
0.4a4.dev10+g471e70b
```

```
$ vint < ~/.vimrc
vint ERROR: nothing to check
usage...
```

**Comment by mike-lloyd03** [comment]
Okay nevermind. vint is working with coc.nvim and I was reading from stdin incorrectly. Should be 

```
$ vint - < ~/.vimrc
```
